### ISSUE TITLE
Add filtering by legislative district

### ISSUE THREAD

**Issue by kmagida110** [ctoec/data-visualization#10]
## Background
OEC reports out to legislators and will need to report on sites in particular legislator's districts. Currently, student data is not geocoded for privacy reasons so the unit of analysis here will only be sites.

## Acceptance Criteria
A filter is created to show the following by legislative district:
- Sites
- Filled Slots
- Open Slots
- Demographics on enrolled students

## Technical Specs
- Sites need to have Geographic coordinates associated with them

**Comment by JordanGuinn** [comment]
Moving forward can you create these tickets from within Zenhub?  That should auto-apply the `dev-team` label, which allows us to see these on our board 🙂

**Comment by kmagida110** [comment]
@JordanGuinn Yup, I think the first time I tried it wasn't joined so it failed and I never tried again.
