### ISSUE TITLE
Create Utilization Charts

### ISSUE THREAD

**Issue by kmagida110** [ctoec/data-visualization#13]
## Background
OEC runs report on site level utilization relative to their available slots and this will make it more visible.

## Acceptance Criteria
Charts are added to Superset (**only** for the July 2020 snapshot) with:
- Available slots by town and site
- Filled slots by town and site
- Geographic distribution of open slots

**Comment by JordanGuinn** [comment]
Why did this suddenly get sprinted?

**Comment by kmagida110** [comment]
@JordanGuinn I thought they were going to go into a dashboard for our meeting this afternoon so upped their priority but it doesn't seem like they will now, I'll ping and discuss before moving next time.

**Comment by JordanGuinn** [comment]
Okay perfect - thank you!
