### ISSUE TITLE
Research Census data fields that should be collected on the legislative district and town level

### ISSUE THREAD

**Issue by kmagida110** [ctoec/data-visualization#21]
## Background
To calculate unmet needs for OEC we will need to have a sense of which fields we want to collect and how easy they are to access.

## Acceptance Criteria
- The census data set that will be used is identified and a way to access it is prototyped.
- A list of fields of Census data is complied with names that can be pulled programmatically or in a direct download from the Census.

## Technical Specs
- Town codes and legislative district codes should be able to be specified in the proposed function call.

## Additional Context
- Python Census API wrapper: https://jtleider.github.io/censusdata/, https://pypi.org/project/CensusData/
- American Community Survey fields: https://www.census.gov/programs-surveys/acs/technical-documentation/code-lists.html

**Comment by JordanGuinn** [comment]
@kmagida110 Have all of these data visualization tickets (or at least the ones that don't involve any dev work) been enumerated in Notion?  Wondering if it's safe for me to delete these out of the dev backlog.

**Comment by kmagida110** [comment]
@JordanGuinn I'm not sure, can we resolve at Week Ahead today?

**Comment by JordanGuinn** [comment]
Sure thing!
