### ISSUE TITLE
Create site level database table

### ISSUE THREAD

**Issue by kmagida110** [ctoec/data-visualization#6]
## Background
This ticket will allow for charts analyzing provider's site information including enrollment, site location and available spaces.

## Acceptance Criteria
- A csv is created and uploaded to Superset that contains the following columns:
  - Provider location data (gathered from OpenStates API ticket)
  - Provider allocated space data (already exists, will just need to be calculated)
  - Unique key for site that matches the site key in enrollment data

**Comment by JordanGuinn** [comment]
Is the takeaway here that we already have this data, and just need to create a CSV out of it?

**Comment by kmagida110** [comment]
@JordanGuinn 
1. We either have the data or can get it through APIs
2. For now table generation will be through an upload to Superset which can ingest CSVs to a database.

**Comment by JordanGuinn** [comment]
@kmagida110 Is this done?  Can this be brought over to the `Done` swimlane if so?

**Comment by kmagida110** [comment]
Yup, I'll move it over
