### ISSUE TITLE
Add Site maps to OEC Dashboard

### ISSUE THREAD

**Issue by kmagida110** [ctoec/data-visualization#8]
## Background
OEC has had demands for a map of their services by location.

## Acceptance Criteria
- Superset has one or more map components based around sites
- Map should inform site location and connect it with the number of enrollments for said sites

## Technical Specs
- Will require the creation of a MapBox API key and the installation of said API key in Superset (config file?)
  - Key already exists - reach out to Kyle for access

**Comment by JordanGuinn** [comment]
Are these maps gonna be providing a general Site location breakdown by region, or do we intend to use other location-based data points here?

**Comment by kmagida110** [comment]
Site location along with the relative size of the sites

**Comment by JordanGuinn** [comment]
Same question - is this done too?

**Comment by kmagida110** [comment]
Same answer, I'll move it
