### ISSUE TITLE
Add filtering by town to Superset dashboard

### ISSUE THREAD

**Issue by kmagida110** [ctoec/data-visualization#9]
## Background
Census data is often best analyzed by town and OEC performs a fair amount of town based analysis. Town level government is also a common stakeholder for OEC.

## Acceptance Criteria
- A town filter is added to Superset to apply to charts on demographics, enrollment, sites and available spaces.

**Comment by JordanGuinn** [comment]
Any distinction between this ticket and https://github.com/ctoec/data-collection/issues/1070?

**Comment by kmagida110** [comment]
No, I just forgot it was in another repo

**Comment by kmagida110** [comment]
Are you OK with me ditching this one?

**Comment by JordanGuinn** [comment]
So long as the necessary reqs from both of these are captured in one of these, sure thing.

**Comment by kmagida110** [comment]
OK, will do
